# Generated by Django 3.1.7 on 2021-10-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='start_date',
        ),
    ]
