# Generated by Django 3.1.7 on 2021-10-21 03:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0003_remove_prospect_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='conversation_stream_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospectdb.conversationstream'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_index'),
        ),
    ]
