# Generated by Django 3.1.7 on 2021-10-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0003_auto_20211012_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='study_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='study_instructions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
