# Generated by Django 3.1.7 on 2021-10-21 03:40

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def update_search_vector(apps, schema_editor):
    ConversationMessage = apps.get_model('prospectdb', 'ConversationMessage')
    ConversationMessage.objects.all().update(search_vector=
                                             SearchVector('text', 'conversation_stream_id'))


class Migration(migrations.Migration):
    dependencies = [
        ('prospectdb', '0004_search_vector'),
    ]

    operations = [
        migrations.RunPython(update_search_vector, elidable=True),
    ]
