# Generated by Django 3.1.7 on 2021-10-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0005_auto_20211012_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospectdb.group'),
        ),
    ]
