# Generated by Django 3.1.7 on 2021-10-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0006_auto_20211012_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='conversation_stream_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='prospectdb.conversationstream'),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='prospectdb.study'),
        ),
    ]
