# Generated by Django 3.1.7 on 2021-10-28 13:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0006_conversationmessageword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectSearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='prospect',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='prospect_search_vector_index'),
        ),
    ]
