# Generated by Django 3.1.7 on 2021-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectdb', '0007_auto_20211012_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_at',
        ),
    ]
